// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grnaemehmvwhduhbqdwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdybmFlbWVobXZ3aGR1aGJxZHdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mjk4MTAsImV4cCI6MjA2NjUwNTgxMH0.r1auh0vSnDBFLAq2wiHHyMwLyBkAMTFr0jgDxQ_jd4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);